### PR TITLE
Converted Training Script Rmarkdown to R

### PR DESCRIPTION
**Pull request by kimaina**
@ibacher Please find the V5 of the training script. The V5 folder contains 2 main files: main.R and helpers.R

### CODE REVIEW

**Review by ibacher — APPROVED** [review]

**Comment by ibacher** [comment]
Feel free to merge this in when you're done. Btw, do we still want to run the Rmarkdown? We can probably figure that out...

**Comment by kimaina** [comment]
> Feel free to merge this in when you're done. Btw, do we still want to run the Rmarkdown? We can probably figure that out...

It would be really great if we can run RMD but not a priority for now

**Comment by kimaina** [comment]
> > Feel free to merge this in when you're done. Btw, do we still want to run the Rmarkdown? We can probably figure that out...
> 
> It would be really great if we can run RMD but not a priority for now

@ibacher How much effort will it be needed? this is key in order to generate summary stats and answer some of the questions being asked here: https://docs.google.com/document/d/19VPb4zxtJVsF77fjn3AFmrPflr6lsz50VIeeqfOz1qU/edit

Also generating some of the var importance and partial dependency plots.

If can expose an R-markdown using an internal IP that can be accessed via VPN that'd be great 
would something like this be possible? https://jsta.github.io/r-docker-tutorial/02-Launching-Docker.html

**Comment by ibacher** [comment]
So, it should basically be trivial to run the Rmarkdown. We can use Docker's volume feature to ensure that the output is written to a directory that is accessible on the host machine. The part that's a little obscure to me is how we could serve it, but maybe a conversation with @corneliouzbett or @drizzentic could get that worked out?

**Pull request merged**
